---
variables:
  HELM_VALUES: |
    mapping:
      host: trino-${CI_MERGE_REQUEST_IID}.dev.capinside.com
    serviceAccount:
      resourceID: ci-${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}-trino-server

helm-chart:
  rules:
    # Execute if triggered via WEB UI
    - if: $CI_PIPELINE_SOURCE == "web"
    # Do not execute on release commit
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /^release: .*/"
      when: never
    # Execute for each merge request
    - if: $CI_MERGE_REQUEST_IID
    # Execute if pushed to default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Execute if tag is created
    - if: $CI_COMMIT_TAG
  stage: test
  trigger:
    include:
      - file: .gitlab-ci-helm.yml
        project: capinside/infrastructure/helm/gitlab-ci-pipeline
    strategy: depend
