branches: main
tagFormat: "${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
        - release: patch
          type: chore
        - release: patch
          type: docs
        - release: minor
          type: feat
        - release: patch
          type: fix
        - release: patch
          type: perf
        - release: patch
          type: phrase
        - release: patch
          type: refa
        - release: patch
          type: "*"
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - section: Miscellaneous Chores
            type: chore
          - section: Documentation
            type: docs
          - section: Features
            type: feat
          - section: Bug Fixes
            type: fix
          - section: Performance
            type: perf
          - section: Phrase
            type: phrase
          - section: Refactorings
            type: refa
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"

  - "@semantic-release/gitlab"

  - - "semantic-release-helm"
    - chartPath: .

  - - "@semantic-release/git"
    - message: "release: ${nextRelease.version}\n\n${nextRelease.notes}"
      assets: ["CHANGELOG.md", "Chart.yaml"]

  - - "semantic-release-slack-bot"
    - branchesConfig:
        - pattern: main
          notifyOnSuccess: true
          notifyOnFail: true

ci: true
debug: true
